BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBB
XXXXXXXXXXXXX

XXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XX
    BBBBBBBBBBBBBB BBBB
    BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
XXXXXXX
BBBBBBBB