BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBB
XXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    BBBBBBBBBBBBBB BBBB
    BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB
XXXXXXX
BBBBBBBB