# Generated by Django 3.2 on 2022-06-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kenmei',
        ),
        migrations.DeleteModel(
            name='Seibetu',
        ),
        migrations.AlterField(
            model_name='user',
            name='kekkonreki',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='kodomo',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyojuchi',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='nenrei',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='osake',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='shokugyo',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='shumi',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='shussin',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='tabako',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40),
        ),
        migrations.DeleteModel(
            name='Kekkonreki',
        ),
        migrations.DeleteModel(
            name='Kodomo',
        ),
        migrations.DeleteModel(
            name='Nenrei',
        ),
        migrations.DeleteModel(
            name='Osake',
        ),
        migrations.DeleteModel(
            name='Shokugyo',
        ),
        migrations.DeleteModel(
            name='Shumi',
        ),
        migrations.DeleteModel(
            name='Tabako',
        ),
    ]
