# Generated by Django 3.2 on 2022-06-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220626_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kekkonreki',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40, verbose_name='kekkonreki'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kodomo',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40, verbose_name='kodomo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyojuchi',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40, verbose_name='kyojuchi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nenrei',
            field=models.CharField(blank=True, max_length=40, verbose_name='nenrei'),
        ),
        migrations.AlterField(
            model_name='user',
            name='osake',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40, verbose_name='osake'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shokugyo',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40, verbose_name='shokugyo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shumi',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40, verbose_name='shumi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shussin',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40, verbose_name='shussin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tabako',
            field=models.CharField(blank=True, choices=[('mikon', '未婚'), ('sibetu', '死別'), ('rikon', '離婚')], max_length=40, verbose_name='tabako'),
        ),
    ]
