# Generated by Django 3.2 on 2022-07-18 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, verbose_name='マッチング許可')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('approached', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approached', to=settings.AUTH_USER_MODEL)),
                ('approaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('approaching', 'approached')},
            },
        ),
    ]
