BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBBBBB
    BBBBBBBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
    BBBBB BBBBBBBBBBBBBBBBBBB
XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBXXXXXXXXXXXXXXXX
            BBBB
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBXXXXXXXXXXXXXXX            
            BBBBB
        XXXXX
    XXXXXX
XXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBB
    XXXXXX
XXXXXXX
XXXXXXX
XXXXXXX

